var navList = {
    "cateList": [{
            "id": 1005000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "居家",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/48c38bac8af3a6b06173bbc0cf6a1852.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1036000,
                    "superCategoryId": 1005000,
                    "showIndex": 1,
                    "name": "夏凉",
                    "frontName": "夏凉床品，舒适一夏",
                    "frontDesc": "夏凉床品，舒适一夏",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/13ff4decdf38fe1a5bde34f0e0cc635a.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008009,
                    "superCategoryId": 1005000,
                    "showIndex": 2,
                    "name": "床品件套",
                    "frontName": "MUJI等品牌制造商出品",
                    "frontDesc": "严格用料，亲肤舒适",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/243e5bf327a87217ad1f54592f0176ec.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008008,
                    "superCategoryId": 1005000,
                    "showIndex": 3,
                    "name": "被枕",
                    "frontName": "守护你的睡眠时光",
                    "frontDesc": "选用优质材料，确保好芯",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/927bc33f7ae2895dd6c11cf91f5e3228.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1015000,
                    "superCategoryId": 1005000,
                    "showIndex": 4,
                    "name": "家具",
                    "frontName": "大师级工艺",
                    "frontDesc": "一级原木，严苛工艺",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4f00675caefd0d4177892ad18bfc2df6.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008016,
                    "superCategoryId": 1005000,
                    "showIndex": 5,
                    "name": "灯具",
                    "frontName": "一盏灯，温暖一个家",
                    "frontDesc": "极简主义，贴近生活的设计",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/c48e0d9dcfac01499a437774a915842b.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008017,
                    "superCategoryId": 1005000,
                    "showIndex": 6,
                    "name": "收纳",
                    "frontName": "选自古驰竹柄原料供应商",
                    "frontDesc": "智慧收纳，抗菌防霉，便利拆卸，小空间的大智慧",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/fdc048e1bf4f04d1c20b32eda5d1dc6e.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008002,
                    "superCategoryId": 1005000,
                    "showIndex": 7,
                    "name": "布艺软装",
                    "frontName": "各种风格软装装点你的家",
                    "frontDesc": "换个软装，换个家",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/8bbcd7de60a678846664af998f57e71c.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1011004,
                    "superCategoryId": 1005000,
                    "showIndex": 8,
                    "name": "家饰",
                    "frontName": "装饰你的家",
                    "frontDesc": "点缀美好生活，品质在于细节",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/ab0df9445d985bf6719ac415313a8e88.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020000,
                    "superCategoryId": 1005000,
                    "showIndex": 9,
                    "name": "旅行用品",
                    "frontName": "出行小物，贴心相伴",
                    "frontDesc": "便携设计，轻便旅途",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/b29a11afa76b9f4a57131555f1a54c77.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1017000,
                    "superCategoryId": 1005000,
                    "showIndex": 10,
                    "name": "宠物",
                    "frontName": "抑菌除味，打造宠物舒适空间",
                    "frontDesc": "出口品质，严选贴合萌宠生活习惯用品。",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/a0352c57c60ce4f68370ecdab6a30857.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1008000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "鞋包配饰",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/9d577dca06b08a69088e9f44f979fa86.png",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1037000,
                    "superCategoryId": 1008000,
                    "showIndex": 1,
                    "name": "行李箱",
                    "frontName": "轻奢行李箱陪你走天下",
                    "frontDesc": "各式行李箱陪你走天下",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/288b0e864a24763bade8e22c0c39ff02.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1056001,
                    "superCategoryId": 1008000,
                    "showIndex": 2,
                    "name": "男士包袋",
                    "frontName": "MK制造商",
                    "frontDesc": "MK制造商",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/cda21c64f3da3fdf6e7989de91a73212.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1056002,
                    "superCategoryId": 1008000,
                    "showIndex": 3,
                    "name": "女士包袋",
                    "frontName": "Alexander McQueen制造商",
                    "frontDesc": "Alexander McQueen制造商",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/5772be58599ae04e05129ceb41aec4f8.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1056003,
                    "superCategoryId": 1008000,
                    "showIndex": 4,
                    "name": "钱包及小皮件",
                    "frontName": "TUMI制造商",
                    "frontDesc": "TUMI制造商",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/03c94770d651fa1f1085466a1d392122.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013000,
                    "superCategoryId": 1008000,
                    "showIndex": 5,
                    "name": "女鞋",
                    "frontName": "女士的优雅魅力",
                    "frontDesc": "UGG制造商出品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/340e0f58cc53085c9198abb044dd615f.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008003,
                    "superCategoryId": 1008000,
                    "showIndex": 6,
                    "name": "男鞋",
                    "frontName": "一双好鞋，才能带你到远方",
                    "frontDesc": "百搭造型，舒适脚感，久穿不累",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4316c2d05745bc90d1f333e363e571bd.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008010,
                    "superCategoryId": 1008000,
                    "showIndex": 7,
                    "name": "拖鞋",
                    "frontName": "穿上拖鞋，回到自我",
                    "frontDesc": "人体工学设计，放松双脚",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/1121696544ed9b0c2a70e82f1088fa0e.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1044000,
                    "superCategoryId": 1008000,
                    "showIndex": 8,
                    "name": "鞋配",
                    "frontName": "关于鞋子的小配件",
                    "frontDesc": "关于鞋子的小配件",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/2d74ae435d8f7fff5ef0b64e653ac257.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008004,
                    "superCategoryId": 1008000,
                    "showIndex": 9,
                    "name": "袜子",
                    "frontName": "优衣库、CK、拉尔夫劳伦制造商",
                    "frontDesc": "优衣库、CK、拉尔夫劳伦制造商",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/f123c74f54d9acff0bd1546c60034814.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1034000,
                    "superCategoryId": 1008000,
                    "showIndex": 10,
                    "name": "丝袜",
                    "frontName": "厚木制造商，秋冬搭配佳品",
                    "frontDesc": "厚木制造商，秋冬搭配佳品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/d82d0bacfd7243c2ad09dbf2513cfcf9.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020008,
                    "superCategoryId": 1008000,
                    "showIndex": 11,
                    "name": "配饰",
                    "frontName": "与众不同的点睛之笔",
                    "frontDesc": "优选设计，让细节显示好品味",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/d835a76e56a88905194f543b67089b4b.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1036001,
                    "superCategoryId": 1008000,
                    "showIndex": 12,
                    "name": "眼镜",
                    "frontName": "实用加时尚，造型百搭单品",
                    "frontDesc": "实用加时尚，造型百搭单品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/97f5f75ea1209dfbb85e91932d26c3ed.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008007,
                    "superCategoryId": 1008000,
                    "showIndex": 13,
                    "name": "围巾件套",
                    "frontName": "戴上它，你的造型才完整",
                    "frontDesc": "严选好材料，亲肤柔软，防风抗寒，温暖不失风度",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/3a8c7ae5b9dc5c1c4b7f2b656abb0279.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1010000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "服装",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/135113d6a43536b717063413fa24d69a.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1015001,
                    "superCategoryId": 1010000,
                    "showIndex": 1,
                    "name": "T恤",
                    "frontName": "自在而潇洒的穿着感",
                    "frontDesc": "立体裁剪，专为国人打造",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/24a7a33cfeac0bb87a737480db79e053.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1078000,
                    "superCategoryId": 1010000,
                    "showIndex": 2,
                    "name": "运动",
                    "frontName": "运动休闲多场景任意切换",
                    "frontDesc": "专业休闲运动风",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/863b1e4a6c84fb33f5d09d91d2a36881.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020010,
                    "superCategoryId": 1010000,
                    "showIndex": 3,
                    "name": "衬衫",
                    "frontName": "细节讲究，合身剪裁",
                    "frontDesc": "挺拔而不束缚",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/94aa4a4814e2a7a97639438f1d52dcee.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1068003,
                    "superCategoryId": 1010000,
                    "showIndex": 4,
                    "name": "牛仔",
                    "frontName": "四季长青款，时尚牛仔风",
                    "frontDesc": "四季长青款，时尚牛仔风",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4948ed874eca5b09f9c064a647a9260f.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1035002,
                    "superCategoryId": 1010000,
                    "showIndex": 5,
                    "name": "裤装",
                    "frontName": "高质感面料，休闲商务两相宜",
                    "frontDesc": "高质感面料",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/a3906045b1367d70f658ce9de03e8193.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1010001,
                    "superCategoryId": 1010000,
                    "showIndex": 6,
                    "name": "内衣",
                    "frontName": "给你贴身的关怀",
                    "frontDesc": "自然染料，亲肤舒适",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/20279e1753e4eedc6e347857acda9681.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1010002,
                    "superCategoryId": 1010000,
                    "showIndex": 7,
                    "name": "内裤",
                    "frontName": "来自李维斯、爱慕等制造商",
                    "frontDesc": "透气洁净，环保染制",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/364269344ed69adafe1b70ab7998fc50.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013006,
                    "superCategoryId": 1010000,
                    "showIndex": 8,
                    "name": "家居服",
                    "frontName": "舒适亲肤",
                    "frontDesc": "居家休闲必备",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/71f391af17fce739a6a57a1eeadbcbf0.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1037007,
                    "superCategoryId": 1010000,
                    "showIndex": 9,
                    "name": "裙装",
                    "frontName": "量身裁体的优雅",
                    "frontDesc": "量身裁体的优雅",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/ae34c149c8d4532e8d04a7b3a9578bcd.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1035000,
                    "superCategoryId": 1010000,
                    "showIndex": 10,
                    "name": "卫衣",
                    "frontName": "舒适百搭，时尚选择",
                    "frontDesc": "舒适百搭，时尚选择",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/97bb55280b8ffa40390f2ee36486314a.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020009,
                    "superCategoryId": 1010000,
                    "showIndex": 11,
                    "name": "外衣",
                    "frontName": "穿出时尚感",
                    "frontDesc": "外衣，是你面对这个世界的铠甲",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/883d89e54a9287569a201eca388a7cda.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1035001,
                    "superCategoryId": 1010000,
                    "showIndex": 12,
                    "name": "针织毛衫",
                    "frontName": "细腻软糯，贴肤的品质之选",
                    "frontDesc": "细腻软糯，贴肤的品质之选",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/cc886f16c8b9893305f1b3b6ad4eb0b1.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1043000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "电器",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/369bfa3656be0771e62b79d181b4433b.png",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1011003,
                    "superCategoryId": 1043000,
                    "showIndex": 1,
                    "name": "生活电器",
                    "frontName": "高性价比的智能小家电",
                    "frontDesc": "生活电器",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4cbfd1f6e50bc808ddf0bbd0ef9f246c.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1023000,
                    "superCategoryId": 1043000,
                    "showIndex": 2,
                    "name": "厨房电器",
                    "frontName": "厨房里的省心小电器",
                    "frontDesc": "省心省力，厨房高效能手",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/521bd0c02d283b80ba49e73ca84df250.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1010003,
                    "superCategoryId": 1043000,
                    "showIndex": 3,
                    "name": "个护健康",
                    "frontName": "个人护理，省心生活",
                    "frontDesc": "个人护理，省心生活",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/19ffe3776ea359bede92c73c6b81bc35.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1022000,
                    "superCategoryId": 1043000,
                    "showIndex": 4,
                    "name": "数码",
                    "frontName": "智能硬件，匠心出品",
                    "frontDesc": "享受安全智能的科技生活",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/3ec003761d346bc866de2ec249d7ff19.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008006,
                    "superCategoryId": 1043000,
                    "showIndex": 5,
                    "name": "影音娱乐",
                    "frontName": "视听盛宴，共享欢乐",
                    "frontDesc": "视听盛宴，共享欢乐",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/a6f0238587bc3126404082e93eeba59f.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1013001,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "洗护",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/14bb4a29498a0f93a1ea001f26fea1dd.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1037001,
                    "superCategoryId": 1013001,
                    "showIndex": 1,
                    "name": "纸品湿巾",
                    "frontName": "和风设计，温和清洁",
                    "frontDesc": "和风设计，温和清洁",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/5ccf97220d69681197a4e82bf5cdc7b5.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1009000,
                    "superCategoryId": 1013001,
                    "showIndex": 2,
                    "name": "家庭清洁",
                    "frontName": "洁净才能带来清爽心情",
                    "frontDesc": "天然材料，温和去除污垢",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/3067ee3e3871d0f9d1b3f3a3d8673e6f.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1037004,
                    "superCategoryId": 1013001,
                    "showIndex": 3,
                    "name": "生理用品",
                    "frontName": "关爱，温柔呵护",
                    "frontDesc": "关爱，私密的呵护",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/b6f93123c2b2ee6f35a378103bba67cf.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008001,
                    "superCategoryId": 1013001,
                    "showIndex": 4,
                    "name": "毛巾",
                    "frontName": "日本皇室专供，内野制造商出品",
                    "frontDesc": "精选长绒棉，出口日本品质标准",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/44ad9a739380aa6b7cf956fb2a06e7a7.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013002,
                    "superCategoryId": 1013001,
                    "showIndex": 5,
                    "name": "美妆",
                    "frontName": "为你的面容添色",
                    "frontDesc": "竹宝堂、资生堂等制造商出品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/aa49c088f74a1c318f1765cc2703495a.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020001,
                    "superCategoryId": 1013001,
                    "showIndex": 6,
                    "name": "面部口腔护理",
                    "frontName": "温和无刺激的呵护",
                    "frontDesc": "天然成分，无化学添加",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/f73df75f334126cf1f3823696ea0663c.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1037002,
                    "superCategoryId": 1013001,
                    "showIndex": 8,
                    "name": "身体护理",
                    "frontName": "呵护肌肤，天然温和",
                    "frontDesc": "呵护肌肤，天然温和",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/810a6d6bcffc740aae58bb6174cf3b73.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020002,
                    "superCategoryId": 1013001,
                    "showIndex": 9,
                    "name": "浴室用具",
                    "frontName": "小工具成就美好浴室",
                    "frontDesc": "环保材料，耐用不发霉",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/50b8792c3190a920f0c8323a0a534735.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013003,
                    "superCategoryId": 1013001,
                    "showIndex": 10,
                    "name": "洗发护发",
                    "frontName": "呵护秀发，柔顺不同发质",
                    "frontDesc": "护发超有效小秘诀",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/a4d0f08f1cee8c3240ea8522d6aa8ffa.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013004,
                    "superCategoryId": 1013001,
                    "showIndex": 11,
                    "name": "香薰",
                    "frontName": "爱马仕集团制造商出品",
                    "frontDesc": "提炼纯净，清雅不腻",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/d43e7af0a6a9385d88be2ca1df679158.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1005002,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "饮食",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/449327dfc891fd40426d7b601a8b1e99.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1087019,
                    "superCategoryId": 1005002,
                    "showIndex": 1,
                    "name": "世界杯美食",
                    "frontName": "世界杯狂欢，看球必点美食",
                    "frontDesc": "世界杯狂欢，看球必点美食",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/d456ccd5ff3daacf40efcab726f3af66.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008015,
                    "superCategoryId": 1005002,
                    "showIndex": 2,
                    "name": "糕点",
                    "frontName": "四季糕点，用心烘焙",
                    "frontDesc": "无人工添加香精、防腐剂",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/93168242df456b5f7bf3c89653b3db76.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005011,
                    "superCategoryId": 1005002,
                    "showIndex": 3,
                    "name": "小食",
                    "frontName": "原香鲜材，以小食之味，带来味蕾惊喜",
                    "frontDesc": "原香鲜材，以小食之味，带来味蕾惊喜",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/663f568475c994358bf31bcb67d122fe.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005010,
                    "superCategoryId": 1005002,
                    "showIndex": 4,
                    "name": "坚果炒货",
                    "frontName": "精选原产地，美味加营养",
                    "frontDesc": "精选原产地，美味加营养",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/6c43063003207168c1d8e83a923e8515.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1027001,
                    "superCategoryId": 1005002,
                    "showIndex": 5,
                    "name": "果干",
                    "frontName": "品尝与收获到的是自然的味道",
                    "frontDesc": "品尝与收获到的是自然的味道",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/60f4ae2beef4754347fa36208f84efab.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1035003,
                    "superCategoryId": 1005002,
                    "showIndex": 6,
                    "name": "肉类零食",
                    "frontName": "真嗜肉者，都爱这一味，佳肴美馔真滋味",
                    "frontDesc": "真嗜肉者，都爱这一味，或麻辣鲜香、或五味俱全，都是佳肴美馔真滋味",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/db3e11b8a6974a253818ae0d6fb2d24e.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005013,
                    "superCategoryId": 1005002,
                    "showIndex": 7,
                    "name": "冲饮",
                    "frontName": "以用料天然之美，尽享闲雅之意",
                    "frontDesc": "以用料天然之美，尽享闲雅之意",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/2919b0d6eec79182cca31dc827f4d00a.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1027000,
                    "superCategoryId": 1005002,
                    "showIndex": 8,
                    "name": "茗茶",
                    "frontName": "一品茶香，品茗即是观心，饮茶涤净尘虑",
                    "frontDesc": "一品茶香，品茗即是观心，饮茶涤净尘虑",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/0c5af0575176c4a3023783bef7a87a0f.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1053001,
                    "superCategoryId": 1005002,
                    "showIndex": 9,
                    "name": "酒水饮料",
                    "frontName": "美酒佳酿，用心典藏",
                    "frontDesc": "美酒佳酿，用心典藏",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/140d6105712a23ecbbcafd72ebbb83d8.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005012,
                    "superCategoryId": 1005002,
                    "showIndex": 10,
                    "name": "食材",
                    "frontName": "天时地利人和，寻找这个时节这个地点的味道",
                    "frontDesc": "天时、地利、人和，寻找这个时节这个地点的味道",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/e050980992725b7932bb3645fe5aec08.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1036003,
                    "superCategoryId": 1005002,
                    "showIndex": 11,
                    "name": "调味",
                    "frontName": "烹饪必备，美食调味",
                    "frontDesc": "烹饪必备，美食调味",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/2ae44a3944f2bc737416e1cff3d4bcef.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1054001,
                    "superCategoryId": 1005002,
                    "showIndex": 12,
                    "name": "滋补保健",
                    "frontName": "营养滋补，只为健康",
                    "frontDesc": "营养滋补，只为健康",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/7b7ca3f7e14280b6bedfbaa0e5a5a831.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008014,
                    "superCategoryId": 1005002,
                    "showIndex": 13,
                    "name": "生鲜",
                    "frontName": "安全配送，新鲜直达",
                    "frontDesc": "安全配送，新鲜直达",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/2245616009de893ece74bbe4be81d9d7.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1005001,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "餐厨",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/89f5056078016a30fa7c0a1180a84bdf.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1007000,
                    "superCategoryId": 1005001,
                    "showIndex": 1,
                    "name": "水具杯壶",
                    "frontName": "精工生产制作，匠人手艺",
                    "frontDesc": "10Q品质控制系统",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/0b244d3575b737c8f0ed7e84c5c4abd2.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005008,
                    "superCategoryId": 1005001,
                    "showIndex": 2,
                    "name": "餐具",
                    "frontName": "餐桌上的舞蹈",
                    "frontDesc": "皇家道尔顿、日本KEYUCA制造商出品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/f109afbb7e7a00c243c1da29991a5aa3.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005007,
                    "superCategoryId": 1005001,
                    "showIndex": 3,
                    "name": "锅具",
                    "frontName": "一口好锅，炖煮生活一日三餐",
                    "frontDesc": "中华铸铁、精选不锈钢、进口珐琅",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4aab4598017b5749e3b63309d25e9f6b.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008011,
                    "superCategoryId": 1005001,
                    "showIndex": 4,
                    "name": "清洁保鲜",
                    "frontName": "真空保鲜，美味不限时",
                    "frontDesc": "让厨房整洁又新鲜，防尘防潮",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/dc4d6c35b9f4abb42d2eeaf345710589.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008012,
                    "superCategoryId": 1005001,
                    "showIndex": 5,
                    "name": "厨房配件",
                    "frontName": "下厨省力小帮手",
                    "frontDesc": "日日使用的物件，制作精良才能更耐用",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/22db4ccbf52dc62c723ac83aa587812a.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1013005,
                    "superCategoryId": 1005001,
                    "showIndex": 6,
                    "name": "刀剪砧板",
                    "frontName": "传统工艺 源自中国刀城",
                    "frontDesc": "厨房实用利器",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/9d481ea4c2e9e6eda35aa720d407332e.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1005009,
                    "superCategoryId": 1005001,
                    "showIndex": 7,
                    "name": "茶具咖啡具酒具",
                    "frontName": "严选精巧器具，轻松冲调",
                    "frontDesc": "严选精巧器具，轻松冲调",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/3d27c4e157c1882eedaf1eff68dd4eeb.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1011000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "婴童",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/218e29990668266f76ee511e2ff2dd4e.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1037005,
                    "superCategoryId": 1011000,
                    "showIndex": 1,
                    "name": "儿童服饰",
                    "frontName": "萌宝的时尚LOOK",
                    "frontDesc": "萌宝的时尚LOOK",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/2d4ff57286fdce725491e02a8e3e0c72.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020003,
                    "superCategoryId": 1011000,
                    "showIndex": 2,
                    "name": "婴幼儿服饰",
                    "frontName": "萌宝穿搭，柔软舒适触感",
                    "frontDesc": "100%纯棉，无荧光剂，严格质检",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/4e50f3c4e4d0a64cd0ad14cfc0b6bd17.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1037006,
                    "superCategoryId": 1011000,
                    "showIndex": 3,
                    "name": "童鞋童包",
                    "frontName": "萌娃的必备鞋包",
                    "frontDesc": "萌娃的必备鞋包",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/dad175edb8590a33938427161939ff3f.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020004,
                    "superCategoryId": 1011000,
                    "showIndex": 4,
                    "name": "婴童洗护",
                    "frontName": "天然，呵护宝宝肌肤",
                    "frontDesc": "给孩子更美好的童年体验",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/c55338691ebd46bee9ebf225f80363ce.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1011001,
                    "superCategoryId": 1011000,
                    "showIndex": 5,
                    "name": "孕产",
                    "frontName": "犬印、Harvest Hills制造商",
                    "frontDesc": "孕育生命的你更值得被爱",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/720aebaa529df9391b95a078dfb2fd5c.png",
                    "iconUrl": "",
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020005,
                    "superCategoryId": 1011000,
                    "showIndex": 6,
                    "name": "寝居",
                    "frontName": "无荧光剂，婴幼儿A类标准",
                    "frontDesc": "始于初心，为爱初色",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/0f3c5ad63139096fd0760219e12149af.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020007,
                    "superCategoryId": 1011000,
                    "showIndex": 7,
                    "name": "喂养",
                    "frontName": "宝宝吃得香，妈妈才放心",
                    "frontDesc": "安全健康，我们执着于每个细节",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/5db40a5bf84c177515610471d4d08687.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1020006,
                    "superCategoryId": 1011000,
                    "showIndex": 8,
                    "name": "玩具",
                    "frontName": "萌宝童趣必备",
                    "frontDesc": "严选材质，安全无害保证",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/7aac7c5819f71345a52a4b9df23d6239.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1034001,
                    "superCategoryId": 1011000,
                    "showIndex": 9,
                    "name": "婴童出行",
                    "frontName": "安全舒适，给宝宝一个快乐童年",
                    "frontDesc": "安全舒适，给宝宝一个快乐童年",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/06bbfb293b6194b27ebdb3350203a1f7.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1019000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "文体",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/72de912b6350b33ecf88a27498840e62.jpg",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1012003,
                    "superCategoryId": 1019000,
                    "showIndex": 1,
                    "name": "文具",
                    "frontName": "找回书写的力量",
                    "frontDesc": "极简设计，环保材质",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/e1743239e41ca9af76875aedc73be7f0.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1008005,
                    "superCategoryId": 1019000,
                    "showIndex": 2,
                    "name": "运动户外",
                    "frontName": "MUJI、Nike等制造商出品",
                    "frontDesc": "踏青出游，便携不误好心情",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/83d22ca3d1c8f94ee23ca96de489864c.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1028001,
                    "superCategoryId": 1019000,
                    "showIndex": 3,
                    "name": "唱片",
                    "frontName": "经典音乐，用心典藏，瑞鸣音乐大师匠心打造",
                    "frontDesc": "瑞鸣音乐大师匠心打造",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/71feb3efd3eaee01a74e8aa78430de9d.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1025000,
                    "superCategoryId": 1019000,
                    "showIndex": 4,
                    "name": "礼品卡",
                    "frontName": "送礼、福利首选",
                    "frontDesc": "传递高品质生活美学",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/bb9232716b2fc96d9bdbac4955360dfa.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1050000,
                    "superCategoryId": 1019000,
                    "showIndex": 6,
                    "name": "游戏点卡",
                    "frontName": "给信仰充值",
                    "frontDesc": "给信仰充值",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/fd0ad6276081767b2ca094f565003264.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1041001,
                    "superCategoryId": 1019000,
                    "showIndex": 8,
                    "name": "我的世界",
                    "frontName": "我的世界游戏周边",
                    "frontDesc": "我的世界游戏周边",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/42db52ecb366dc7b763fa852252e38ad.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1033000,
                    "superCategoryId": 1019000,
                    "showIndex": 9,
                    "name": "梦幻西游",
                    "frontName": "梦幻西游精品周边",
                    "frontDesc": "梦幻西游精品周边",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/f0698297aaac41b778c1ea65eefb8b34.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1036004,
                    "superCategoryId": 1019000,
                    "showIndex": 10,
                    "name": "大话西游",
                    "frontName": "大话西游正版周边",
                    "frontDesc": "大话西游正版周边",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/b60618db213322bdc2c5b1208655bd7e.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1039000,
                    "superCategoryId": 1019000,
                    "showIndex": 11,
                    "name": "阴阳师",
                    "frontName": "欧气，快到寮里来",
                    "frontDesc": "快到寮里来",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/d7150580b1f432a2fb12a7f695c4c6e8.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1018000,
                    "superCategoryId": 1019000,
                    "showIndex": 12,
                    "name": "游戏表情",
                    "frontName": "网易游戏表情周边",
                    "frontDesc": "网易游戏表情周边",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/5f4144d6c39717404b9ffc87190fb6c4.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1069000,
                    "superCategoryId": 1019000,
                    "showIndex": 13,
                    "name": "影视周边",
                    "frontName": "漫威DC系列影视周边",
                    "frontDesc": "漫威DC系列影视周边",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/1a8c366f7c75e062da4ecb71ab1535de.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1069001,
                    "superCategoryId": 1019000,
                    "showIndex": 14,
                    "name": "动漫周边",
                    "frontName": "迪斯尼、初音系列动漫周边商品",
                    "frontDesc": "迪斯尼、初音系列动漫周边商品",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/171694fd3636d80d3bb69410e06a65c4.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        },
        {
            "id": 1065000,
            "superCategoryId": 0,
            "showIndex": 0,
            "name": "特色区",
            "frontName": "",
            "frontDesc": null,
            "bannerUrl": "https://yanxuan.nosdn.127.net/d9f2d29a543a817a1af0bc682ba20ff2.png",
            "iconUrl": null,
            "level": null,
            "subCateList": [{
                    "id": 1065001,
                    "superCategoryId": 1065000,
                    "showIndex": 1,
                    "name": "日本馆",
                    "frontName": "日本制造家居好物",
                    "frontDesc": "日本制造家居好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/24a5a967a30f170219ac95882b2c1157.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065003,
                    "superCategoryId": 1065000,
                    "showIndex": 2,
                    "name": "韩国馆",
                    "frontName": "韩国制造精巧好物",
                    "frontDesc": "韩国制造精巧好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/e6859ab74c8b256c3693a5b4f0f723ba.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065005,
                    "superCategoryId": 1065000,
                    "showIndex": 3,
                    "name": "东南亚馆",
                    "frontName": "东南亚特色好物",
                    "frontDesc": "东南亚特色好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/aa84314477c47c94b2db958eb8f1fdd9.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065004,
                    "superCategoryId": 1065000,
                    "showIndex": 4,
                    "name": "欧美馆",
                    "frontName": "欧美制造好物",
                    "frontDesc": "欧美制造好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/e51196686ef891d49c94fc0dd86f4b56.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065002,
                    "superCategoryId": 1065000,
                    "showIndex": 5,
                    "name": "澳新馆",
                    "frontName": "澳大利亚、新西兰制造天然好物",
                    "frontDesc": "澳大利亚、新西兰制造天然好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/671f360d034f3c5c82ef104a1e0380f2.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065006,
                    "superCategoryId": 1065000,
                    "showIndex": 6,
                    "name": "智造馆",
                    "frontName": "网易智造数码好物",
                    "frontDesc": "网易智造数码好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/a13a24413e66474cc7b0551984cfe9d4.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065007,
                    "superCategoryId": 1065000,
                    "showIndex": 7,
                    "name": "春风馆",
                    "frontName": "网易原创情趣用品，专为亚洲年轻人设计",
                    "frontDesc": "网易原创情趣用品，专为亚洲年轻人设计",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/178c0e02e625cdff474efafc55f96468.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065008,
                    "superCategoryId": 1065000,
                    "showIndex": 8,
                    "name": "味央馆",
                    "frontName": "网易味央精品黑猪肉",
                    "frontDesc": "网易味央精品黑猪肉",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/7821524529a067bba5bc5ef08c113fe2.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065009,
                    "superCategoryId": 1065000,
                    "showIndex": 9,
                    "name": "云音乐周边馆",
                    "frontName": "网易云音乐周边发售",
                    "frontDesc": "网易云音乐周边发售",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/ac59e7caab4a9b12f6d9e07c2c58257c.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                },
                {
                    "id": 1065010,
                    "superCategoryId": 1065000,
                    "showIndex": 10,
                    "name": "严选推荐馆",
                    "frontName": "严选推荐精品好物",
                    "frontDesc": "严选推荐精品好物",
                    "bannerUrl": "https://yanxuan.nosdn.127.net/9401b24e23f3507ff8b08414ab978eb1.png",
                    "iconUrl": null,
                    "level": "L2",
                    "subCateList": []
                }
            ]
        }
    ],
}